### ISSUE TITLE
Ensure client session is always established

### ISSUE THREAD

**Issue by aldocatella** [takenet/messaginghub-client-js#14]
We could make sure that the transport is connected and that the Lime session is established inside the MessagingHub client.

**Comment by andre-takenet** [comment]
Done ;)

**Comment by arthur-xavier** [comment]
Good!

But I see the test coverage dropped a little. Let's try to keep it 100% as the project is still kinda small. Also, regarding the commit messages, please read the [Contribution guidelines](https://github.com/takenet/messaginghub-client-js/blob/master/CONTRIBUTING.md), and make sure to commit using `npm run commit`, or else the library won't get automatically published/released using semantic release.
