### ISSUE TITLE
MessageHubClient should allow empty constructor

### ISSUE THREAD

**Issue by andre-takenet** [takenet/messaginghub-client-js#17]
Uri and Transport could default to ws://msging.net:8081' and Lime.WebSocketTransport, respectively, since these values will rarely be changed.

**Comment by andrebires** [comment]
You now can use the [MessagingHub.ClientBuilder](https://github.com/takenet/messaginghub-client-js/blob/master/src/ClientBuilder.js) class to build your client with the conventional values.
