### ISSUE TITLE
Use a mountebank for fake tests with lime

### ISSUE THREAD

**Issue by Ridermansb** [takenet/messaginghub-client-js#5]

**Comment by Ridermansb** [comment]
Works local but in travis fail.  I post this questions [on stackoverflow](http://stackoverflow.com/questions/34510772/mountebank-docker) and [google groups](https://groups.google.com/forum/#!topic/mountebank-discuss/m-UrVZBR1sQ) but at the moment, I not receive answers.

**Comment by arthur-xavier** [comment]
Tests now use a local tcp mock server.
